'use client';

import React, { useState } from 'react';
import styles from '../CourseWizard.module.css';

interface QuizQuestion {
    question: string;
    options: string[];
    answer: number;
}

interface Step6QuizReviewProps {
    data: any;
    quiz?: QuizQuestion[];
}

export default function Step6QuizReview({ data, quiz }: Step6QuizReviewProps) {
    const [expandedSection, setExpandedSection] = useState<string | null>('section-1');

    // Use generated quiz if available, otherwise fallback to empty or mock
    const questions = quiz || [];

    return (
        <div className={styles.stepWrapper}>
            <h2 className={styles.stepTitle}>Review Quiz Questions</h2>
            <p className={styles.stepSubtitle}>
                Review and edit the quiz questions generated by AI.
            </p>

            <div className={styles.quizReviewContainer}>
                {/* Header Row */}
                <div className={styles.quizHeaderRow}>
                    <div className={styles.quizHeaderLeft}>
                        <div className={styles.quizSectionTitle}>Editable quiz questions</div>
                        <div className={styles.quizSubtitle}>{questions.length} Questions Generated</div>
                    </div>
                    <button className={styles.btnRegenerate}>
                        Regenerate Quiz
                    </button>
                </div>

                {/* Flat Question List */}
                <div className={styles.questionListWrapper}>
                    {questions.length === 0 ? (
                        <div className={styles.emptyState}>
                            No questions generated. Please go back and regenerate the course.
                        </div>
                    ) : (
                        questions.map((q, index) => (
                            <div key={index} className={styles.questionCard}>
                                <div className={styles.questionHeader}>
                                    <div className={styles.questionText}>
                                        {index + 1}. {q.question}
                                    </div>
                                    <button className={styles.btnEdit}>Edit</button>
                                </div>
                                <div className={styles.optionList}>
                                    {q.options.map((opt, optIndex) => (
                                        <div key={optIndex} className={styles.optionItem}>
                                            <div
                                                className={`${styles.radioCircle} ${q.answer === optIndex ? styles.radioSelected : ''}`}
                                                style={q.answer === optIndex ? { background: '#48BB78', borderColor: '#48BB78' } : {}}
                                            />
                                            {opt}
                                            {q.answer === optIndex && <span style={{ marginLeft: 8, fontSize: 12, color: '#48BB78', fontWeight: 600 }}>(Correct)</span>}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ))
                    )}
                </div>
            </div>
        </div>
    );
}
